# Generated by Django 5.1.4 on 2024-12-22 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPGlobalIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('constituents', models.IntegerField()),
                ('value', models.FloatField()),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('divisor', models.FloatField(blank=True, null=True)),
                ('daily_return', models.FloatField()),
                ('dividend', models.FloatField(blank=True, null=True)),
                ('adjusted_market_cap', models.FloatField(blank=True, null=True)),
                ('adjusted_divisor', models.FloatField(blank=True, null=True)),
                ('adjusted_constituents', models.IntegerField()),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=50)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('last_update', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexConstituent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='spglobal.spglobalindex')),
            ],
        ),
    ]
